[General]
    # What should be the maximum width of an elevator cabin? Higher numbers may cause lag.
    # Allowed range: 1 ~ 15 - Default: 7
    maxCabinHorizontalSize = 7

    # What should be the maximum height of an elevator cabin? Higher numbers may cause lag.
    # Allowed range: 1 ~ 15 - Default: 7
    maxCabinVerticalSize = 7

