name: Project Info
run-name: "Project Info #${{ github.run_number }}"

env:
  RELEASE_TYPE: "release"
  MINECRAFT_VERSION: "1.12.2"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  info:
    name: Project Info
    runs-on: ubuntu-latest
    outputs:
      project_version: ${{ steps.project_version.outputs.tag }}
      project_name: ${{ steps.project_name.outputs.value }}
      project_full_name: ${{ steps.project_name.outputs.value }}-${{ steps.project_version.outputs.tag }}
      changelog: ${{ steps.changelog.outputs.description }}
      diff: ${{ steps.read_diff.outputs.diff }}
      release_type: ${{ env.RELEASE_TYPE }}
      minecraft_version: ${{ env.MINECRAFT_VERSION }}
      exists: ${{ steps.check_tag.outputs.exists }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
    
      - name: ðŸ”Ž Check pakku-lock.json
        id: check_pakku_lock
        shell: bash
        run: |
          if [ ! -f pakku-lock.json ]; then
            echo "âŒ Could not find pakku-lock.json" && exit 1
          else
            echo "âœ”ï¸ pakku-lock.json"
          fi

      - name: ðŸ”Ž Check pakku.json
        id: check_pakku
        shell: bash
        run: |
          if [ ! -f pakku.json ]; then
            echo "âŒ Could not find pakku.json" && exit 1
          else
            echo "âœ”ï¸ pakku.json"
          fi

      - name: Get latest tag
        id: get_latest_tag
        shell: bash
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          if [ -z "$latest_tag" ]; then
            echo "âŒ Latest tag not found" && exit 1
          else
            echo "âœ”ï¸ Latest tag found: $latest_tag"
          fi

      - name: ðŸ”Ž Check pakku-lock.json in previous tag
        id: check_pakku_lock_prev
        shell: bash
        run: |
          if ! git ls-tree -r $latest_tag -- ./pakku-lock.json &> /dev/null; then
            echo "âŒ File pakku-lock.json not found in previous tag" && exit 1
          else
            echo "âœ”ï¸ File pakku-lock.json found in previous tag"
          fi

      - name: Copy pakku-lock.json from previous tag
        id: copy_pakku_lock_prev
        shell: bash
        run: |
          git show tags/$latest_tag:./pakku-lock.json > ./pakku-lock-prev.json
          if [ -s ./pakku-lock-prev.json ]; then
            echo "âœ”ï¸ File pakku-lock-prev.json created"
          else
            echo "âŒ Error: File pakku-lock-prev.json is empty or not created" && exit 1
          fi

      - name: Download pakku.jar
        id: download_pakku
        shell: bash
        run: |
          curl https://github.com/juraj-hrivnak/pakku/releases/latest/download/pakku.jar -o pakku.jar -L -J
          echo "âœ”ï¸ Downloaded pakku.jar "

      - name: Run pakku diff
        id: run_pakku_diff
        shell: bash
        run: |
          java -jar pakku.jar diff -v --markdown PROJECTS_DIFF.md ./pakku-lock-prev.json ./pakku-lock.json
          if [ -f PROJECTS_DIFF.md ]; then
            echo "âœ”ï¸ Comparison completed"
          else
            echo "âŒ Error: File PROJECTS_DIFF.md not created" && exit 1
          fi

      - name: Read PROJECTS_DIFF.md to variable
        id: read_diff
        shell: bash
        run: |
          echo "ðŸ“ Reading PROJECTS_DIFF.md to variable..."
          DIFF_CONTENT=$(cat PROJECTS_DIFF.md)
          echo "âœ”ï¸ Diff content read to variable"
          echo "diff=${DIFF_CONTENT}" >> $GITHUB_OUTPUT
  

      - name: Get Project Name
        id: project_name
        uses: ActionsTools/read-json-action@v1.0.5
        with:
          file_path: "pakku.json"
          prop_path: "name"

      - name: Get Project Version
        id: project_version
        uses: ActionsTools/read-json-action@v1.0.5
        with:
          file_path: "pakku.json"
          prop_path: "version"

      - name: Changelog Parser
        id: changelog
        uses: coditory/changelog-parser@v1.0.2
        with:
          path: CHANGELOG.md

      - name: Upload Diff
        id: diff
        if: ${{ steps.read_diff.outputs.diff != '' }}
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Mods-diff
          path: PROJECTS_DIFF.md

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check_tag
        with:
          tag: ${{ steps.project_version.outputs.value }}
          
      - name: Generate Github Summary
        run: |
          echo "ðŸ“ƒ **Name**: ${{ steps.project_name.outputs.value }}" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ“ƒ **Release**: ${{ steps.project_version.outputs.value }}" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ“ƒ **Release Type**: ${{ env.RELEASE_TYPE }}" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ“ƒ **Game Version**: ${{ env.MINECRAFT_VERSION }}" >> $GITHUB_STEP_SUMMARY
          
          echo "${{ steps.changelog.outputs.description }}" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ steps.read_diff.outputs.diff != '' }}" ]; then
            echo "${{ steps.read_diff.outputs.diff }}" >> $GITHUB_STEP_SUMMARY
          fi

  build:
    needs: [info]
    if: needs.info.outputs.exists != 'true'
    uses: ./.github/workflows/build.yml
    with:
      project_version: ${{ needs.info.outputs.project_version }}
      project_name: ${{ needs.info.outputs.project_name }}
      project_full_name: ${{ needs.info.outputs.project_full_name }}
      changelog: ${{ needs.info.outputs.changelog }}
      diff: ${{ needs.info.outputs.diff }}
      release_type: ${{ needs.info.outputs.release_type }}
      minecraft_version: ${{ needs.info.outputs.minecraft_version }}
    secrets: inherit